[package]
name = "git-pit"
version = "0.1.0"
edition = "2024"

[dependencies]
smol = "2.0.2"
async-tungstenite = "0.31.0"
git2 = "0.20.2"
#mews = {version = "0.5.2", features = ["rt_smol"]}

[[bin]]
name="git-pit"
path = "src/server/main.rs"
